---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
```
### U4163418 ATRO executions
```{r}
library(dplyr)
library(tidyr)
library(lubridate)
library(knitr)
library(stringr)
library(xml2)

trade_file_tbl <- tibble(fn=c(
'/home/user/Downloads/Trade_Confirms_2020.xml',
'/home/user/Downloads/Trade_Confirms_2021.xml',
'/home/user/Downloads/Trade_Confirms_2022.xml',
'/home/user/Downloads/Trade_Confirms_2023.xml',
'/home/user/Downloads/Trade_Confirms_2024.xml',
'/home/user/Downloads/Trade_Confirms_2025.xml')
)
trade_file_tbl %>% print()


df0 <- trade_file_tbl %>% group_by(fn) %>%
  group_modify( ~ {
    as_list(read_xml(.y$fn) |> xml_ns_strip()) %>% 
      as_tibble() %>% 
      unnest_wider(FlexQueryResponse) %>%
      unnest_wider(FlexStatement) %>%
      unnest_longer(TradeConfirms)
  }) %>% ungroup()

df0 %>%  glimpse()

df0 %>% count(TradeConfirms_id,sort=TRUE)
```
```{r }
df1 <- df0 %>% 
  filter(TradeConfirms_id=='TradeConfirm') %>%
  mutate(row=1:n()) %>%
  group_by(row) %>%
      group_modify(~ {
        .x$TradeConfirms[[1]] %>% attributes() %>% stack() %>%
          rename(key = ind, value = values) %>%
          filter(value != '', value!='0', value!='0.0') %>%
          select(key, value)
      }) %>% ungroup()  %>%
  pivot_wider(names_from = key, values_from = value) 

df1 %>% glimpse()

df1 <- df1 %>%
  # remove 11/22/2024 treasury overfill resulting in liquidation (subsequently cxld)
  filter(!str_detect(buySell,'BUY (Ca.)|SELL (Ca.)'),
         !str_detect(tradeID,'6936118135|6936592373|6936579823|6936580138|6936580560'))
```
```{r }
df2 <- df1 %>%
  distinct(
    conid,
    symbol,
    description,
    assetCategory,
    subCategory,
    securityID,
    securityIDType,
    cusip,
    isin,
    figi,
    listingExchange,
    underlyingSymbol,
    issuerCountryCode,
    multiplier
  )
df3 <- df1 %>%
  select(conid,row,accountId,currency,transactionType,tradeID,orderID,
  execID,brokerageOrderID,extExecID,orderTime,
  dateTime,reportDate,settleDate,tradeDate,exchange,buySell,quantity,
  price,amount,proceeds,netCash,netCashWithBillable,commission,
  brokerExecutionCommission,thirdPartyExecutionCommission,thirdPartyClearingCommission,
  thirdPartyRegulatoryCommission,commissionCurrency,code,orderType,levelOfDetail,isAPIOrder)
  
df2 %>% distinct(
    conid,
    symbol,
    description,
    assetCategory,
    subCategory,
    multiplier
) %>% print()

invisible(
  df2 %>% distinct(conid, symbol, description,multiplier) %>%
    group_by(conid, symbol, description,multiplier) %>%
    group_walk( ~
                  {
                    .y %>% print()
                    df3 %>% inner_join(.y %>% select(conid,multiplier)) %>%
                      mutate(
                        dateTime = ymd_hms(dateTime),
                        year = year(dateTime),
                        month = month(dateTime),
                        quantity = replace_na(as.numeric(quantity), 0),
                        price = replace_na(as.numeric(price), 0),
                        commission = replace_na(as.numeric(commission), 0),
                        netCash = replace_na(as.numeric(netCash), 0),
                        multiplier=replace_na(as.numeric(multiplier),1)
                      ) %>%
                      select(year,
                             month,
                             dateTime,
                             #tradeID,
                             exchange,
                             buySell,
                             quantity,
                             price,
                             commission,
                             netCash,
                             multiplier) %>%
                      arrange(year,month,dateTime) %>%
                      group_by(year, month) %>%
                      group_walk( ~ {
                        .y %>% print()
                        .x %>%
                          group_by(buySell) %>%
                          summarise(quantity=sum(quantity),netCash=sum(netCash),commission=sum(commission),
                                    multiplier=max(multiplier),
                                    price=(netCash-commission)/quantity/multiplier,.groups = 'drop') %>%
                          select(buySell,quantity,price,commission,netCash) %>%
                          kable(
                            col.names = c(
                              'Action',
                              'Quantity',
                              'Price',
                              'Commission',
                              'Net Cash'
                            )
                          ) %>% print()
                        .x %>%
                          select(-multiplier)%>%
                          kable(
                            col.names = c(
                              'Date Time',
                              'Exchange',
                             #'TradeID',
                              'Action',
                              'Quantity',
                              'Price',
                              'Commission',
                              'Net Cash'
                            )
                          ) %>% print()
                      })
                  }) %>%  ungroup()
)

df3 %>% count(buySell,sort=TRUE)
df3 %>% glimpse()
df3 %>% filter(!(buySell %in% c('BUY','SELL'))) %>% glimpse()
df3 %>% filter(reportDate=='20241122') %>% glimpse()
```
