---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE)
```
### U4163418 ATRO executions
```{r results='hide'}
library(dplyr)
library(tidyr)
library(lubridate)
library(knitr)
library(xml2)

# /home/user/Downloads/Trade_Confirms_2020.xml
# /home/user/Downloads/Trade_Confirms_2021.xml
# /home/user/Downloads/Trade_Confirms_2022.xml
# /home/user/Downloads/Trade_Confirms_2023.xml
# /home/user/Downloads/Trade_Confirms_2024.xml
# /home/user/Downloads/Trade_Confirms_2025.xml


xml_address <- '/home/user/Downloads/Trade_Confirms_2025.xml'

xmlList <- as_list(read_xml(xml_address) |> xml_ns_strip())


df0 <- xmlList %>% as_tibble() %>% unnest_wider(FlexQueryResponse) %>%
  unnest_wider(FlexStatement) %>%
  unnest_longer(TradeConfirms)
df0 %>%  glimpse()

df0 %>% count(TradeConfirms_id,sort=TRUE)
```
```{r results='hide'}
df1 <- df0 %>% 
  filter(TradeConfirms_id=='TradeConfirm') %>%
  mutate(row=1:n()) %>%
  group_by(row) %>%
      group_modify(~ {
        .x$TradeConfirms[[1]] %>% attributes() %>% stack() %>%
          rename(key = ind, value = values) %>%
          filter(value != '', value!='0', value!='0.0') %>%
          select(key, value)
      }) %>% ungroup()  %>%
  pivot_wider(names_from = key, values_from = value) 

df1 %>% glimpse()
```
```{r results='hide'}
df2 <- df1 %>% 
  distinct(assetCategory,subCategory,symbol,
           description,conid,securityID,securityIDType,
           cusip,isin,figi,listingExchange,underlyingSymbol,
           issuerCountryCode,multiplier)
df3 <- df1 %>%
  select(row,accountId,currency,transactionType,tradeID,orderID,
  execID,brokerageOrderID,extExecID,orderTime,
  dateTime,reportDate,settleDate,tradeDate,exchange,buySell,quantity,
  price,amount,proceeds,netCash,netCashWithBillable,commission,
  brokerExecutionCommission,thirdPartyExecutionCommission,thirdPartyClearingCommission,
  thirdPartyRegulatoryCommission,commissionCurrency,code,orderType,levelOfDetail,isAPIOrder)
  
df2 %>% glimpse()
df3 %>% glimpse()
```
```{r }
df3 %>%
  mutate(dateTime=ymd_hms(dateTime),
         thirdPartyExecutionCommission=replace_na(as.numeric(thirdPartyExecutionCommission),0)) %>%
  select(dateTime,exchange,buySell,quantity,price,brokerExecutionCommission,
         thirdPartyExecutionCommission,thirdPartyClearingCommission,thirdPartyRegulatoryCommission) %>%
  kable(col.names = c('Date Time','Exch','Action','Qty','Prc','IBKR',
                      '3rd Ex','3rd Clr', '3rd Reg')) 
  
```

Third-party execution commissions are inconsistent for limit-on-open vs limit-on-close orders.
