---
title: "SEC rule 605 file"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
rpt_digits <- 3
```

```{r load}
library(dplyr)
library(knitr)
library(lubridate)
library(ggplot2)

load('rule605.rda')


symbol_df <- data %>%
  filter(month==max(month)) %>%
  mutate(month=ymd(sprintf('%s01',month)))%>%
  group_by(symbol,month) %>%
  summarise(cus_sprd = sum(filled*aes),
            mkt_sprd = cus_sprd + sum(impr_shr*impr_amnt*2),
            filled = sum(filled),
            aes=cus_sprd/filled,
            mes=mkt_sprd/filled, 
            value = (aes/2 - .0035)*filled, # hoping for half-spread less cost
            ratio=aes/mes, .groups = 'drop') %>%
  slice_max(order_by=value,n=10) 
# symbol_df


sum_data <- data %>%
  #inner_join(symbol_df %>% select(symbol),by='symbol') %>%
  #filter(symbol %in% symbol_df$symbol) %>%
  mutate(month=ymd(sprintf('%s01',month)))%>%
  group_by(symbol,month) %>%
  summarise(cus_sprd = sum(filled*aes),
            mkt_sprd = cus_sprd + sum(impr_shr*impr_amnt*2),
            filled = sum(filled),
            aes=cus_sprd/filled,
            mes=mkt_sprd/filled, 
            ratio=aes/mes, 
            value = (aes/2 - .0035)*filled, # max collected is half spread less cost
            .groups = 'drop') %>%
  group_by(month) %>%
  arrange(-value) %>% mutate(rank=1:n()) %>% ungroup() %>% filter(rank<=10)
```
```{r rpt0,results='asis'}
plt_data <- sum_data %>% inner_join(sum_data %>% filter(rank<=10) %>% distinct(symbol),by='symbol') %>%
  group_by(month)%>%
  group_modify(~{
    .x %>% filter(rank<=10) %>% 
      summarise(cus_sprd=sum(cus_sprd), mkt_sprd=sum(mkt_sprd), filled=sum(filled), ratio=cus_sprd/mkt_sprd,
                value=sum(value))
  }) %>% ungroup() 
plt_data %>% 
  ggplot(aes(month,value)) + 
  geom_line() + labs(title='Value') 
plt_data %>% 
  ggplot(aes(month,ratio)) + 
  scale_y_continuous(limits = c(0, 1)) + 
  geom_line() + labs(title='Ratio') 

cat('\n\\newpage  \n')
```
```{r rpt,results='asis',fig.height=9,fig.width=6.5}
plt2_data <- sum_data %>% inner_join(sum_data %>% filter(rank<=10) %>% distinct(symbol),by='symbol') %>%
  group_by(month)%>%
  group_modify(~{
    .x %>% filter(rank<=10) 
  }) %>% ungroup() %>%
  group_by(symbol) %>%
  mutate(lbl=if_else(#value==max(value) & 
    value>3e5,symbol,'')) %>%
  mutate(symbol=factor(symbol,levels=(sum_data %>% distinct(symbol))$symbol))

plt2_data %>%
  ggplot(aes(month,value,fill=symbol,label=lbl)) + 
  geom_col(show.legend = FALSE,color='white')+coord_flip() +
  geom_text(color='white',size=2,position = position_stack(vjust=.5))
cat('\n\\newpage  \n')

sum_data %>% inner_join(sum_data %>% filter(rank<=10) %>% distinct(symbol),by='symbol') %>%
  group_by(month)%>%
  group_walk(~{
    .y %>% kable() %>% print()
    .x %>% filter(rank<=10) %>% 
      summarise(cus_sprd=sum(cus_sprd), mkt_sprd=sum(mkt_sprd), filled=sum(filled), ratio=cus_sprd/mkt_sprd,
                value=sum(value)) %>%
      kable( digits = c(rep(0,3),4,0),
            format.args = list(big.mark=',')) %>% 
      print()
    .x %>% filter(rank<=10) %>% arrange(rank) %>% 
      kable(digits=c(rep(0,4),rep(4,3),rep(0,1)),
            format.args = list(big.mark=',')) %>% 
      print()
    cat('\n\\newpage  \n')
  })


```
