---
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
  md_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(knitr)
library(lubridate)
library(rjson)
library(stringr)
library(tidyjson)
library(tidyr)
library(adagio)
```

```{r read, echo=FALSE}
load('trades.rda')
load('margin.rda')

rank_df %>% glimpse()

category_df <- trade_df %>% distinct(symbol,primary) %>%
  inner_join(margin_df %>% distinct(symbol,stockType),by='symbol')


tmp1_df <- margin_df %>%
#
# IBKR .0015 (3-20 million shares / month)
#
# Regulatory Fees
#   SEC Transaction Fee: USD 0.00 * Value of Aggregate Sales
#   FINRA Trading Activity Fee: USD 0.000166 * Quantity Sold
#   FINRA Consolidated Audit Trail Fees: USD 0.000035 * Quantity
#
# Clearing Fees
#   NSCC, DTC Fees: USD 0.00020 per share  
  mutate(fees = 0.0015 + 0.0000278/2*price + 0.000166/2 + .000035 + .0002,
         minoff = fees,
         whole = ceiling(minoff*100)/100,
         half=ceiling((minoff-.005)*100)/100 + .005,
         margin = ipct/100 * price
) %>%
  select(symbol,price,fees,minoff,whole,half,margin,ipct,equity)

tmp2_df <- rank_df %>%
  select(-c(close,comm,value,rank))

summary_df <- category_df %>%
  inner_join(tmp1_df, by = 'symbol') %>%
  inner_join(tmp2_df, by = 'symbol') %>%
  mutate(
    value = volume * (sd_sprd - fees),
    shrLmt = ceiling(pmax(avgshr, 234) / 2),
    usage = shrLmt * margin,
    one = 1
  ) %>% filter(count > 100000,
               stockType == 'COMMON',
               primary == 'NASDAQ',
               sd_sprd > pmax(half, whole)) 
  
hours_df <- margin_df %>% distinct(liquidHours) %>%
  mutate(sod=ymd_hm(word(liquidHours,1,sep='-'))+dminutes(10),
         eod=ymd_hm(word(liquidHours,2,sep='-'))-dminutes(11),
         day_str=sprintf('%04d%02d%02d',year(sod),month(sod),day(sod)),
         sod_str=sprintf('+sod %02d:%02d:%02d',hour(sod),minute(sod),second(sod)),
         eod_str=sprintf('+eod %02d:%02d:%02d',hour(eod),minute(eod),second(eod))
         ) %>% select(-c(sod,eod))

rm(margin_df,rank_df,routing_ratio,trade_df,category_df,tmp1_df,tmp2_df)


today_df <- summary_df
#orig_equity <- today_df$equity[[1]]
#equity <-  orig_equity # * 1.5
#(is <- mknapsack(w=today_df$margin,p=today_df$value,cap=equity))
invisible(is <- mknapsack(w=today_df$one,p=today_df$value,cap=30))
today_df <- bind_cols(today_df,tibble(ksack=is$ksack)) %>%
  filter(ksack==1)


cmdLine_df <- today_df %>%
  arrange(-value) %>%
  mutate(clientId=1:n()+1000,cmd =  sprintf('%.0f %s %.0f %.2f %.3f', clientId,
    symbol, shrLmt*2,whole,half)) %>%
  select(cmd)



output <- bind_rows(
  bind_rows(tibble(symbol='SPY',pos_limit=0,trading='off'),today_df %>%
  arrange(-value)) %>%
    mutate(text = sprintf('%s %.0f %s', symbol, pos_limit, trading),
           watch = sprintf('DES,%s,STK,SMART/AMEX,,,,,', symbol)) %>%
    select(text, watch)
) 

cmd_fn <- sprintf('%s.cmd',hours_df$day_str)
watch_fn <- sprintf('%s.lst',hours_df$day_str)
write(cmdLine_df$cmd,file=cmd_fn)
output <- output %>% drop_na()
write(output$watch,file=watch_fn)
```
```{r results='asis',echo=FALSE}

cat(sprintf('  \n\\newpage  \n### Command line args `%s`  \n',cmd_fn))
```

```{r comment='',echo=FALSE}
cat(readLines(cmd_fn), sep = '\n')
```

\newpage
today_df
```{r echo=FALSE}
today_df %>% 
  arrange(-count) %>%
  select(symbol,volume,count,minoff,stockType,primary,sd_sprd) %>%
  arrange(-sd_sprd) %>%
  filter(stockType=='COMMON',primary=='NASDAQ') %>%
  print(n=Inf)
  #glimpse()

today_df %>% 
  filter(stockType=='COMMON',primary=='NASDAQ',sd_sprd > pmax(half,whole)) %>%
  select(symbol,minoff,sd_sprd,half,whole) %>%
  arrange(-sd_sprd) %>%
  print(n=Inf)

```
\newpage
```{r}
invisible( lapply(ls(),{function (x) 
  {
  cat(sprintf('\n\n%s\n',x))
  get(x)%>%glimpse()
  }}))

```
