---
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document: default
  md_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(knitr)
library(lubridate)
library(rjson)
library(stringr)
library(tidyjson)
library(tidyr)
library(adagio)
```

```{r read, echo=FALSE}
load('trades.rda')
load('margin.rda')


n_avg_units <- 1
min_comm <- .35
comm_per_shr <- .0015 # .002 # .001  
min_visible_size <- 100
min_trade_qty <- ceiling(min_comm / comm_per_shr) + min_visible_size

today_df <- rank_df %>%
  inner_join(margin_df, by = 'symbol') %>%
  inner_join(trade_df %>% distinct(symbol,primary),by='symbol') %>%
  filter(stockType!="ETF") %>%
  mutate(
    pos_limit = n_avg_units * round(avgshr)+99,
    margin = .5 * avgshr * price * ipct / 100,
    adjval = value / margin,
    trading = 'on'
  ) %>%
  arrange(-adjval) %>%
  arrange(-value) %>%
  filter(margin>0,value>0,count>100000
  #,stockType=='COMMON') 
  ,primary=='NASDAQ')


usage <- 0
orig_equity <- today_df$equity[[1]]
equity <-  orig_equity * 1.5

```
```{r solve, echo=FALSE, results='hide'}
# (is <- mknapsack(w=today_df$margin,p=today_df$value,cap=equity))
# which(is$ksack == 1)
# 
# today_df <- today_df[sample(nrow(today_df)),]
# (is <- mknapsack(w=today_df$margin,p=today_df$value,cap=equity))
# which(is$ksack == 1)

today_df <- today_df %>% arrange(-adjval)
(is <- mknapsack(w=today_df$margin,p=today_df$value,cap=equity))
which(is$ksack == 1)

```
\newpage
```{r report0, echo=FALSE}
today_df <- bind_cols(today_df,tibble(ksack=is$ksack)) %>%
  arrange(-value) 
# %>% 
#   mutate(
#     pos_limit = pmax(min_trade_qty, round(n_avg_units * avgshr)),
#     margin = pos_limit * price * ipct / 100,
#     adjval = value / margin,
#     trading = 'on'
#   ) 

considered_df <- today_df %>%
  select(
    symbol,
    sd_sprd,
    price,
    avgshr,
    pos_limit,
    ipct,
    margin,
    value,
    rank
  ) %>% 
  arrange(-value) %>% slice_head(n=40) 
```
\newpage
```{r report1, echo=FALSE}

today_df <- today_df %>%
  filter(ksack==1) %>%
  mutate(usage = cumsum(margin),
         commfee = 0.0015 + 0.0000278/2*price + 0.000166/2 + .0000405,
         minoff = 2*commfee,
         whole = ceiling(minoff*100)/100,
         half=ceiling((minoff-.005)*100)/100 + .005
#IBKR 3,000,001 - 20,000,000   0.0015
#SEC Transaction Fee: USD 0.0000278 * Value of Aggregate Sales
#FINRA Trading Activity Fee: USD 0.000166 * Quantity Sold
#FINRA Consolidated Audit Trail Fees: USD 0.000035 * Quantity to 0.000046 * Quantity
) %>%
  select(
    symbol,
    primary,
    stockType,
    sd_sprd,
    price,
    minoff,
    whole,
    half,
    avgshr,
    pos_limit,
    ipct,
    trading,
    #margin,
    #usage,
    value,
    #adjval,
    rank
    #,count
  ) %>%   slice_head(n=30) # TWS 32 max - 1 monitor - 1 reserved for emergency eject


hours_df <- margin_df %>% distinct(liquidHours) %>%
  mutate(sod=ymd_hm(word(liquidHours,1,sep='-'))+dminutes(10),
         eod=ymd_hm(word(liquidHours,2,sep='-'))-dminutes(11),
         day_str=sprintf('%04d%02d%02d',year(sod),month(sod),day(sod)),
         sod_str=sprintf('+sod %02d:%02d:%02d',hour(sod),minute(sod),second(sod)),
         eod_str=sprintf('+eod %02d:%02d:%02d',hour(eod),minute(eod),second(eod))
         ) %>% select(-c(sod,eod))


```

```{r calc, echo=FALSE, results='asis'}
cat(sprintf('  \n### Equity %.0f (using %.0f)\n',orig_equity,equity))
cat(sprintf('  \n### Top market making stocks %s to %s',as.character(dates_df$min_date),as.character(dates_df$max_date)))
# see https://www.interactivebrokers.com/en/pricing/commissions-stocks.php?re=amer

today_df %>%
  select(-c(whole,half,trading)) %>%
  kable(digits = c(0,0,0,3,2,3,0,0,1,0,0,1),
        format.args = list(big.mark = ','))

today_df %>%
  summarise(value=sum(value)) %>% kable(digits = 0, format.args = list(big.mark=','))

cmdLine_df <- today_df %>%
  mutate(,clientId=1:n()+1000,cmd =  sprintf('%.0f %s %.0f %.2f %.3f', clientId,
    symbol, avgshr,whole,half))

save(cmdLine_df,file='cmdLine_df.rda')


output <- bind_rows(
  bind_rows(tibble(symbol='SPY',pos_limit=0,trading='off'),today_df) %>%
    mutate(text = sprintf('%s %.0f %s', symbol, pos_limit, trading),
           watch = sprintf('DES,%s,STK,SMART/AMEX,,,,,', symbol)) %>%
    select(text, watch)
) 

cmd_fn <- sprintf('%s.cmd',hours_df$day_str)
watch_fn <- sprintf('%s.lst',hours_df$day_str)
write(cmdLine_df$cmd,file=cmd_fn)
output <- output %>% drop_na()
write(output$watch,file=watch_fn)

cat(sprintf('  \n\\newpage  \n### Command line args `%s`  \n',cmd_fn))
```

```{r comment='',echo=FALSE}
cat(readLines(cmd_fn), sep = '\n')
```

```{r echo=FALSE,results='asis'}
cat(sprintf('  \n\\newpage  \n### Considered list \n'))
considered_df %>% kable(caption="Considered",digits=c(0,3,2,0,0,0,0,0,0))
```
